### ISSUE TITLE
Wrong File Name

### ISSUE THREAD

**Issue by edo9k** [arjunmahishi/vanilla-pwa#3]
This line tries to cache `css/main.js`, if I'm not mistaken it should be trying to cache `css/main.css`.

https://github.com/arjunmahishi/vanilla-pwa/blob/5e9be054e9379d6d87b1657e162da279bab3af2d/skeleton/service-worker.js#L9

**Comment by arjunmahishi** [comment]
You are right! Thanks

**Comment by arjunmahishi** [comment]
Addressed this in 90c2eba5efdaba9aab58d89816e68c945f5df188 
Thanks again!
